[project]
name = "partle-backend"
version = "0.1.0"
description = "FastAPI backend for Partle"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Rubén Jiménez Mejías", email = "ruben.jimenezmejias@gmail.com" }
]
dependencies = [
    "fastapi>=0.95.0",
    "uvicorn[standard]>=0.22.0",
    "SQLAlchemy>=2.0",
    "pydantic>=2.0",
    "httpx>=0.28.1",
    "alembic>=1.13",
    "psycopg2-binary>=2.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app"]
