"""Add creator_id to Product

Revision ID: d33c35409f15
Revises: 1e11c10e8f53
Create Date: 2025-06-20 18:00:36.196392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d33c35409f15"
down_revision: Union[str, Sequence[str], None] = "1e11c10e8f53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column("products", sa.Column("creator_id", sa.Integer(), nullable=True))
    op.execute("UPDATE products SET creator_id = 1")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column("creator_id", nullable=False)
        batch_op.create_foreign_key("fk_products_creator_id_users", "users", ["creator_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_constraint("fk_products_creator_id_users", type_="foreignkey")
        batch_op.drop_column("creator_id")
    # ### end Alembic commands ###
